[project]
name = "iteraa"
version = "1.0.0"
description = "A package to conduct accelerated archetypal analysis with an iterative approach."
authors = [
    {name = "Jonathan Yik Chang Ting"},
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.9.1",
    "seaborn>=0.13.2",
    "natsort>=8.4.0",
    "pandas>=2.2.2",
    "scikit-learn>=1.5.1",
    "scipy>=1.14.0",
    "numpy<2.0.0",
    "spams-bin>=2.6.10",
]

[dependency-groups]
dev = [
    "pytest>=8.2.2,<10.0.0",
    "pytest-cov>=5.0.0",
    "jupyter>=1.0.0",
    "myst-nb>=1.1.1",
    "sphinx-autoapi>=3.1.2",
    "sphinx-rtd-theme>=2.0.0",
    "python-semantic-release>=9.17.0",
]

[tool.semantic_release]
version_toml = [
    "pyproject.toml:project.version",
]                                                    # version location
branch = "main"                                      # branch to make releases of
changelog_file = "CHANGELOG.md"                      # changelog file
build_command = "uv build"                           # build dists 

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
